# Generated by Django 4.2.3 on 2023-08-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0003_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='timeOfCreate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='timeOfUpdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
