# Generated by Django 4.2.3 on 2023-08-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0006_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='tradePossibility',
            field=models.BooleanField(default=False, help_text='Отметьте, уместен ли торг', verbose_name='Торг'),
        ),
    ]
